#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(furrr)
  library(argparse)
  library(rtracklayer)
  library(tidyverse)})
options(future.globals.maxSize=1*1024^4)  # 1 terabyte

DESCRIPTION <- str_c(
  "Add gene type records to a GTF file, overwriting previous existing gene ",
  "type records, inferring gene from gene_id of existing non-gene type ",
  "records.")
KEEP_ATTRIBUTES_DEFAULT <- "gene_name,gene_type,tag"
KEEP_ATTRIBUTES_HELP <- str_glue(
  "Comma-delimited list of attributes to keep, in addition to gene_id. ",
  "The value of an attribute in a newly constructed gene type record is the ",
  "comma-delimited list of unique values for that attribute for all non-gene ",
  "type records in the input GTF with that the same gene_id. For example, the ",
  "default value is \"{KEEP_ATTRIBUTES_DEFAULT}\".")

main <- function() {
  parser <- ArgumentParser(description=DESCRIPTION)
  parser$add_argument("input", help="Input GTF file")
  parser$add_argument(
    "--threads", "-t", default=1,
    help="Number of parallel sessions. The default is 1 (don't parallelize)")
  parser$add_argument(
    "--keep-attributes",
    help=KEEP_ATTRIBUTES_HELP, default=KEEP_ATTRIBUTES_DEFAULT)
  parser$add_argument("output", help="Output GTF file")

  args <- parser$parse_args()
  plan(multisession, workers=args$threads)
  export.gff2(
    agr2gtf(args$input, str_split_1(args$keep_attributes, ",")),
    args$output)
}

agr2gtf <- function(gtf_in, keep_attributes) {
  # Check and account for possibly empty gene_id
  gtf <- import.gff2(gtf_in)
  stopifnot("gene_id" %in% colnames(mcols(gtf)))
  is_na_gene <- is.na(mcols(gtf)$gene_id)
  if (any(is_na_gene))
    warning(str_glue(
      "{x} of total {y} rows have no gene_id; these will be skipped...",
      x=sum(is_na_gene), y=length(is_na_gene)))
  gtf_bygene <- split(gtf, mcols(gtf)$gene_id)

  # Check and account for genes on different chromosomes and strands
  has_multiple_seq_strand <- gtf_bygene %>%
    map_lgl(
      ~length(unique(seqnames(.x))) != 1 || length(unique(strand(.x))) != 1)
  if (any(has_multiple_seq_strand))
    warning(str_glue(
      "{x} of total {y} genes lie on multiple sequences or strands; ",
      "these will be skipped",
      x=sum(has_multiple_seq_strand), y=length(has_multiple_seq_strand)))
  gtf_bygene_sameseqstrand <- subset(gtf_bygene, !has_multiple_seq_strand)

  # Check and account for pre-existing rows of type "gene"
  has_row_with_gene_type <- gtf_bygene_sameseqstrand %>%
    map_lgl(~"gene" %in% mcols(.x)$type)
  if (any(has_row_with_gene_type))
    warning(str_glue(
      "{x} of total {y} genes already have a \"gene\" feature; overwriting...",
      x=sum(has_row_with_gene_type, na.rm=TRUE),
      y=length(has_row_with_gene_type)))
  gtf_bygene_sans_generow <- gtf_bygene_sameseqstrand %>%
    map(~subset(.x, mcols(.x)$type != "gene"))

  # Create a row of type "gene" and populate some of its mcols. I don't use
  # GenomicRanges::union because that only takes the union of overlapping
  # ranges, but a gene can have non-overlapping transcripts. For example, human
  # novel transcript ENSG00000290385.1 has non-overlapping transcripts
  # ENST00000440163.1# and ENST00000455464.7.
  gtf_genes_sans_mcols <- gtf_bygene_sans_generow %>%
    future_map(
    ~GRanges(
      seqnames=unique(seqnames(.x)),
      ranges=IRanges(min(start(.x)), max(end(.x))),
    strand=unique(strand(.x))),
    .progress=TRUE)
  gtf_genes_mcols_only <- gtf_bygene_sans_generow %>%
    names() %>%
    future_map(
      function(.name) {
        .mcols_orig <- gtf_bygene_sans_generow[[.name]] %>% as_tibble()
        .mcol_new <- tibble(
          source=.mcols_orig$source %>% unique() %>% str_flatten(","),
          type="gene", gene_id=.name)
        for (att in keep_attributes) {
          .mcol_new[[att]] <- .mcols_orig[[att]] %>%
            unique() %>% str_flatten(",")}
        .mcol_new },
      .progress=TRUE)
  gtf_genes <- future_pmap(
    list(gtf_genes_sans_mcols, gtf_genes_mcols_only),
    function(.x, .y) { mcols(.x) <- .y; .x },
    .progress=TRUE)

  # Interleave the new gene rows into original non-gene rows
  gtf_bygene_with_generow <- future_pmap(
    list(gtf_genes, gtf_bygene_sans_generow), c, .progress=TRUE)
  message()  # future_* progress bars do not end with a linebreak

  gtf_bygene_with_generow %>% purrr::reduce(c)
}

if (sys.nframe() == 0) {
  options(warn=1)  # Print warnings as they occur
  main() }
